# Generated by Django 3.1.3 on 2020-11-16 20:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=150)),
                ('name_place', models.CharField(max_length=50)),
                ('place_rating', models.FloatField(max_length=3)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SelectCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_city', models.CharField(choices=[('CHE', 'Cheboksary'), ('GUS', 'Gus-khrustalny')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wander.place')),
                ('history', models.CharField(max_length=120)),
            ],
            bases=('wander.place',),
        ),
        migrations.CreateModel(
            name='PosterEvent',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wander.place')),
                ('date_event_start', models.DateField(default=django.utils.timezone.now)),
                ('date_event_end', models.DateField(default=None, null=True)),
                ('name_event', models.CharField(default='add_name_event', max_length=30)),
                ('ended', models.BooleanField(default=False)),
            ],
            bases=('wander.place',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wander.place')),
            ],
            bases=('wander.place',),
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wander.selectcity', verbose_name='places'),
        ),
    ]
