# Generated by Django 3.1.2 on 2020-10-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=150)),
                ('name_place', models.CharField(max_length=50)),
                ('place_rating', models.FloatField(max_length=2)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SelectCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_city', models.CharField(choices=[('CHE', 'Cheboksary'), ('GUS', 'Gus-khrustalny')], default=('CHE', 'Cheboksary'), max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('places_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wander.places')),
                ('history', models.CharField(max_length=120)),
            ],
            bases=('wander.places',),
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('places_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wander.places')),
                ('date_event', models.DateField()),
            ],
            bases=('wander.places',),
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('places_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wander.places')),
            ],
            bases=('wander.places',),
        ),
        migrations.AddField(
            model_name='places',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='wander.selectcity'),
        ),
    ]
