# Generated by Django 3.1.3 on 2020-11-16 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wander', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='date_event',
        ),
        migrations.AddField(
            model_name='poster',
            name='date_event_end',
            field=models.DateField(default=datetime.datetime(2020, 11, 16, 12, 33, 8, 887350, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='poster',
            name='date_event_start',
            field=models.DateField(default=datetime.datetime(2020, 11, 16, 12, 33, 8, 887350, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='poster',
            name='name_event',
            field=models.CharField(default='add_name_event', max_length=30),
        ),
        migrations.AlterField(
            model_name='places',
            name='place_rating',
            field=models.FloatField(max_length=3),
        ),
    ]
