# Generated by Django 3.1.3 on 2020-11-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wander', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posterevent',
            table='poster_event',
        ),
    ]
