# Generated by Django 3.1.3 on 2020-12-28 19:58

from django.db import migrations, models
import wander.models


class Migration(migrations.Migration):

    dependencies = [
        ('wander', '0003_auto_20201217_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='image',
            field=models.ImageField(default='img/default.jpg', upload_to=wander.models.image_path_attraction),
        ),
        migrations.AddField(
            model_name='place',
            name='image_map',
            field=models.ImageField(default='img/map/default.jpg', upload_to=wander.models.image_map_path),
        ),
        migrations.AddField(
            model_name='posterevent',
            name='image',
            field=models.ImageField(default='img/default.jpg', upload_to=wander.models.image_path_posterevent),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='img/default.jpg', upload_to=wander.models.image_path_restaurant),
        ),
    ]
